import { Injectable } from '@angular/core';
import { BehaviorSubject } from 'rxjs';

export type Idioma = 'es' | 'en';

const textos: Record<Idioma, Record<string, string>> = {
  es: {
    app_title: 'Gestoria de Inventario y Ventas',
    logout: 'Salir',
    dashboard: 'Dashboard',
    inventory: 'Inventario',
    sales: 'Ventas',
    users_roles: 'Usuarios y Roles',
    providers: 'Proveedores',
    purchases: 'Compras',
    expiry: 'Caducidad',
    login_title: 'Iniciar Sesion',
    login_subtitle: 'Accede con tus credenciales de empleado o administrador.',
    user: 'Usuario',
    password: 'Contrasena',
    enter: 'Entrar',
    dashboard_subtitle: 'Vista general del rendimiento diario y acumulado del supermercado.',
    todays_sales: 'Ventas del dia',
    total_accumulated: 'Total acumulado',
    low_stock_alerts: 'Alertas stock bajo',
    daily_sales_trend: 'Tendencia diaria de ventas',
    products_inventory: 'Inventario de Productos',
    inventory_subtitle: 'Controla stock, precio y disponibilidad en tiempo real.',
    total_products: 'Total productos',
    total_stock: 'Stock total',
    inventory_value: 'Valor inventario',
    new_product: 'Nuevo producto',
    name: 'Nombre',
    price: 'Precio',
    stock: 'Stock',
    save_product: 'Guardar producto',
    inventory_list: 'Listado de inventario',
    sales_management: 'Gestion de Ventas',
    sales_subtitle: 'Registra operaciones y revisa el historico de ingresos.',
    registered_sales: 'Ventas registradas',
    new_sale: 'Nueva venta',
    date: 'Fecha',
    register_sale: 'Registrar venta',
    sales_history: 'Historico de ventas',
    actions: 'Acciones',
    delete_sale: 'Eliminar venta',
    users_management: 'Gestion de Usuarios y Roles',
    email: 'Email',
    role: 'Rol',
    active: 'Activo',
    save: 'Guardar',
    yes: 'Si',
    no: 'No',
    providers_module: 'Modulo de Proveedores',
    provider_name: 'Nombre proveedor',
    contact: 'Contacto',
    category: 'Categoria',
    purchases_module: 'Modulo de Compras',
    purchases_subtitle: 'Productos por debajo de stock minimo y sugerencia de reposicion.',
    generate_purchase_order: 'Generar pedido de compra',
    minimum: 'Minimo',
    suggested_quantity: 'Cantidad sugerida',
    expiry_control: 'Control de Caducidad',
    expiry_subtitle: 'Productos que caducan en menos de 7 dias.',
    expires: 'Caduca',
    days_left: 'Dias restantes',
    name_required: 'El nombre es obligatorio y debe tener al menos 2 caracteres.',
    price_required: 'El precio debe ser mayor que 0.',
    stock_required: 'El stock no puede ser negativo.',
    date_required: 'La fecha es obligatoria.',
    total_required: 'El total no puede ser negativo.',
    err_products_load: 'No se pudieron cargar los productos.',
    err_product_create: 'No se pudo crear el producto.',
    ok_product_create: 'Producto creado correctamente.',
    err_sales_load: 'No se pudieron cargar las ventas.',
    err_sale_create: 'No se pudo registrar la venta.',
    err_sale_delete: 'No se pudo eliminar la venta.',
    ok_sale_create: 'Venta registrada correctamente.',
    ok_sale_delete: 'Venta eliminada correctamente.',
    err_dashboard_summary: 'No se pudo cargar el resumen del dashboard.',
    err_dashboard_trend: 'No se pudo cargar la tendencia de ventas.',
    err_users_load: 'No se pudo cargar usuarios (requiere rol Admin).',
    err_user_create: 'No se pudo crear el usuario.',
    ok_user_create: 'Usuario creado correctamente.',
    err_providers_load: 'No se pudo cargar proveedores.',
    err_provider_create: 'No se pudo crear el proveedor.',
    err_purchase_list: 'No se pudo cargar la lista de pedido (requiere rol Admin).',
    err_purchase_create: 'No se pudo generar el pedido de compra.',
    ok_purchase_create: 'Pedido de compra generado correctamente.',
    err_expiry_load: 'No se pudieron cargar los productos proximos a caducar.',
    err_login: 'Credenciales incorrectas o usuario sin acceso.',
    access_key: 'Clave de acceso',
    access_key_required: 'La clave debe tener al menos 4 caracteres.',
    contact_required: 'El contacto debe tener al menos 4 caracteres.',
    category_required: 'La categoria debe tener al menos 2 caracteres.',
    saving: 'Guardando...',
    ok_provider_create: 'Proveedor creado correctamente.',
    ok_user_delete: 'Usuario eliminado correctamente.',
    err_user_delete: 'No se pudo eliminar el usuario.',
    ok_provider_delete: 'Proveedor eliminado correctamente.',
    err_provider_delete: 'No se pudo eliminar el proveedor.',
    remove_from_list: 'Quitar de la lista',
    ok_purchase_item_remove: 'Producto quitado de la lista.',
  },
  en: {
    app_title: 'Inventory and Sales Manager',
    logout: 'Logout',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    sales: 'Sales',
    users_roles: 'Users & Roles',
    providers: 'Suppliers',
    purchases: 'Purchases',
    expiry: 'Expiry',
    login_title: 'Sign In',
    login_subtitle: 'Log in with your employee or admin credentials.',
    user: 'User',
    password: 'Password',
    enter: 'Sign in',
    dashboard_subtitle: 'Daily and accumulated supermarket performance overview.',
    todays_sales: 'Today sales',
    total_accumulated: 'Total accumulated',
    low_stock_alerts: 'Low stock alerts',
    daily_sales_trend: 'Daily sales trend',
    products_inventory: 'Product Inventory',
    inventory_subtitle: 'Control stock, price and availability in real time.',
    total_products: 'Total products',
    total_stock: 'Total stock',
    inventory_value: 'Inventory value',
    new_product: 'New product',
    name: 'Name',
    price: 'Price',
    stock: 'Stock',
    save_product: 'Save product',
    inventory_list: 'Inventory list',
    sales_management: 'Sales Management',
    sales_subtitle: 'Register operations and review income history.',
    registered_sales: 'Registered sales',
    new_sale: 'New sale',
    date: 'Date',
    register_sale: 'Register sale',
    sales_history: 'Sales history',
    actions: 'Actions',
    delete_sale: 'Delete sale',
    users_management: 'Users and Roles Management',
    email: 'Email',
    role: 'Role',
    active: 'Active',
    save: 'Save',
    yes: 'Yes',
    no: 'No',
    providers_module: 'Suppliers Module',
    provider_name: 'Supplier name',
    contact: 'Contact',
    category: 'Category',
    purchases_module: 'Purchases Module',
    purchases_subtitle: 'Products below minimum stock and replenishment suggestion.',
    generate_purchase_order: 'Generate purchase order',
    minimum: 'Minimum',
    suggested_quantity: 'Suggested quantity',
    expiry_control: 'Expiry Control',
    expiry_subtitle: 'Products expiring in less than 7 days.',
    expires: 'Expires',
    days_left: 'Days left',
    name_required: 'Name is required and must have at least 2 characters.',
    price_required: 'Price must be greater than 0.',
    stock_required: 'Stock cannot be negative.',
    date_required: 'Date is required.',
    total_required: 'Total cannot be negative.',
    err_products_load: 'Products could not be loaded.',
    err_product_create: 'Product could not be created.',
    ok_product_create: 'Product created successfully.',
    err_sales_load: 'Sales could not be loaded.',
    err_sale_create: 'Sale could not be registered.',
    err_sale_delete: 'Sale could not be deleted.',
    ok_sale_create: 'Sale registered successfully.',
    ok_sale_delete: 'Sale deleted successfully.',
    err_dashboard_summary: 'Dashboard summary could not be loaded.',
    err_dashboard_trend: 'Sales trend could not be loaded.',
    err_users_load: 'Users could not be loaded (Admin role required).',
    err_user_create: 'User could not be created.',
    ok_user_create: 'User created successfully.',
    err_providers_load: 'Suppliers could not be loaded.',
    err_provider_create: 'Supplier could not be created.',
    err_purchase_list: 'Purchase list could not be loaded (Admin role required).',
    err_purchase_create: 'Purchase order could not be generated.',
    ok_purchase_create: 'Purchase order generated successfully.',
    err_expiry_load: 'Expiring products could not be loaded.',
    err_login: 'Incorrect credentials or user without access.',
    access_key: 'Access key',
    access_key_required: 'Access key must have at least 4 characters.',
    contact_required: 'Contact must have at least 4 characters.',
    category_required: 'Category must have at least 2 characters.',
    saving: 'Saving...',
    ok_provider_create: 'Supplier created successfully.',
    ok_user_delete: 'User deleted successfully.',
    err_user_delete: 'User could not be deleted.',
    ok_provider_delete: 'Supplier deleted successfully.',
    err_provider_delete: 'Supplier could not be deleted.',
    remove_from_list: 'Remove from list',
    ok_purchase_item_remove: 'Product removed from the list.',
  }
};

@Injectable({ providedIn: 'root' })
export class IdiomaService {
  private readonly claveIdioma = 'idioma_app';
  private readonly idiomaActualSubject = new BehaviorSubject<Idioma>(this.obtenerIdioma());
  readonly idiomaActual$ = this.idiomaActualSubject.asObservable();

  obtenerIdioma(): Idioma {
    return localStorage.getItem(this.claveIdioma) === 'en' ? 'en' : 'es';
  }

  cambiarIdioma(): void {
    const nuevoIdioma: Idioma = this.idiomaActualSubject.value === 'es' ? 'en' : 'es';
    localStorage.setItem(this.claveIdioma, nuevoIdioma);
    this.idiomaActualSubject.next(nuevoIdioma);
  }

  traducir(clave: string): string {
    const idioma = this.idiomaActualSubject.value;
    return textos[idioma][clave] ?? clave;
  }
}
